### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by AriaFantom** [melody-bot/discord-redis-cache#1]
This version is not published in npm how to download

**Comment by git-kush** [comment]
Hey there thanks for taking interest in this project. The version is published in npm [here](https://www.npmjs.com/package/discord-redis-cache). And by the way, this project is a clone of the original [discord.js-redis](https://www.npmjs.com/package/@puyodead1/discord.js-redis) package, but we found that it was unmaintained since a long time so we decided to create our own version of it for our bot- [Melody](https://top.gg/bot/809283972513267752)

You can use it by running `npm install --save discord-redis-cache` and require it in your bot's code -> 

```
const redis = require('discord.js-redis')({
  host: '127.0.0.1' // these options can be found on redis.js.org
});

const client = new discord.Client();
redis(client);

client.login('token');```

**Comment by git-kush** [comment]
I guess the issue is resolved now
